service: dropshipping-backend
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_USER: ${env:PG_USER}
    PG_PASSWORD: ${env:PG_PASSWORD}
    PG_DB: ${env:PG_DB}
    OPENOBSERVE_URL: ${env:OPENOBSERVE_URL}
    OPENOBSERVE_PASSWORD: ${env:OPENOBSERVE_PASSWORD}
    OPENOBSERVE_USERNAME: ${env:OPENOBSERVE_USERNAME}

plugins:
  - serverless-esbuild

functions:
  createSalesOrder:
    handler: src/handlers/sales/createSalesOrder.handler
    events:
      - http:
          path: sales/create
          method: post
  
  greet:
    handler: src/handlers/greet.handler
    events:
      - http:
          path: greet
          method: get

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['pg']
    target: 'node20'
    platform: 'node'
    concurrency: 10
