service: dropshipping-backend
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_USER: ${env:PG_USER}
    PG_PASSWORD: ${env:PG_PASSWORD}
    PG_DB: ${env:PG_DB}

plugins:
  - serverless-esbuild

functions:
  createSalesOrder:
    handler: src/handlers/sales/createSalesOrder.handler
    events:
      - http:
          path: sales/create
          method: post

  createPurchaseOrder:
    handler: src/handlers/purchase/createPurchaseOrder.handler
    events:
      - http:
          path: purchase/create
          method: post

  fulfillOrder:
    handler: src/handlers/fulfillment/fulfillOrder.handler
    events:
      - http:
          path: fulfill
          method: post

  sendInvoice:
    handler: src/handlers/sales/sendInvoice.handler
    events:
      - http:
          path: sales/invoice
          method: post

  itemReceipt:
    handler: src/handlers/purchase/itemReceipt.handler
    events:
      - http:
          path: purchase/receipt
          method: post

  createMemo:
    handler: src/handlers/memo/createMemo.handler
    events:
      - http:
          path: memo/create
          method: post

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['pg']
    target: 'node20'
    platform: 'node'
    concurrency: 10
